name: sample_action

on:
  schedule:
  - cron: "0 12 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository content
        uses: actions/checkout@v2 # Checkout the repository content to github runner.

      - name: Setup Python Version
        uses: actions/setup-python@v2
        with:
          python-version: '3.10.6' # Install the python version needed

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi        

      - name: Execute Python script # Run the run.py to get the latest data
        env:
            TEST_ENV_VAR: ${{ secrets.TEST_ENV_VAR }}
        run: |
          python small_scraper/run.py
